language: swift
osx_image: xcode9.1
xcode_workspace: PlayerControls

before_install:
- brew update
- brew install sourcery
- brew cask install fastlane
- git submodule update --init --recursive

script:
- fastlane verify
